spring:
  application:
    name: bank
  output:
    ansi:
      enabled: always
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  main:
    banner-mode: off
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/