server:
  port: 8081
  servlet:
    context-path: /
    
spring:
  application:
    name: bank
  output:
    ansi:
      enabled: always

  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
