version: '3.7'

volumes: 
  rabbitmq:
  redis:

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.8.3-management-alpine
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia
      - ./scripts/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - "8700:15672"
      - "5671:5671"
      - "5672:5672" 
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 123
      # RABBITMQ_DEFAULT_VHOST: my_virtual_host
      TZ: "@timezone@"

  redis:
    image: redis:5.0.8-alpine
    container_name: redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9410:9410"
      - "9411:9411"
    environment: 
      - "TZ=@timezone@"
      - "RABBIT_URI:amqp://quest@rabbitmq:5672"
    depends_on: 
      - rabbitmq



