server:
  port: 8888

spring:
  main:
 #   lazy-initialization: true
    banner-mode: off
  output:
    ansi:
      enabled: always
  profiles:
    active:
    - native
  devtools:
    add-properties: false
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/configs