server:
  port: 8383

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: buytrip-servicediscovery

---

spring:
  application:
    name: buytrip-servicediscovery
  profiles:
    - dev