server:
  servlet:
    context-path: /

spring:
  application:
    name: buytrip
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
 

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: error


