server:
  servlet:
    context-path: /

spring:
  application:
    name: buytrip
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/ 

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: error


