bank:
  link: http://localhost:8081/pagamentos

spring:
  application:
    name: buytrip-process
  output:
    ansi:
      enabled: ALWAYS
  main:
    banner-mode: OFF
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/


---

spring:
  profiles:
  - test
  main:
    lazy-initialization: true
    banner-mode: OFF
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
 

