bank:
  link: http://localhost:8081/pagamentos
  
spring:
  application:
    name: buytrip-process
  output:
    ansi:
      enabled: always

---

spring:
  profiles:
  - test
  main:
    lazy-initialization: true
    banner-mode: off
 

