bank:
  link: http://localhost:8081/pagamentos

# http://localhost:8185/actuator/bindings
management:
  endpoints:
    web:
      exposure:
        include:
          - bindings


spring:
  application:
    name: buytrip-process
  output:
    ansi:
      enabled: ALWAYS
  main:
    banner-mode: OFF


---

spring:
  profiles:
  - test
  main:
    lazy-initialization: true
    banner-mode: OFF
 

