@host = http://localhost:8180

###

{{host}}

###

POST {{host}}
Content-Type: application/json

{
    "codigoPassagem":11,
    "numeroCartao": 12345678,
    "codigoSeguranca":90,
    "valorPassagem":50
}

