name: BuyTrip CI Automerge

on:

  pull_request:
    branches: [master]
    types: [opened, synchronize, closed]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge no buytrip-ci-automerge
        uses: "pascalgn/automerge-action@80acb0f883348dcfd0e526288f7d27a12b9333be"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "Tested"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
