name: BuyTrip CI

on:
  
  push:
    branches-ignore: [master, homolog]
  pull_request:
    branches: 
      - homolog
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Maven Package
      # run: mvn -B clean package --file pom.xml
      run: mvn -version

  pull-request:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request to homolog
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""                                  
        destination_branch: "homolog"                      
        pr_title: "Pulling ${{ github.ref }} into homolog" 
        pr_label: ""

        github_token: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    needs: [pull-request]
    runs-on: ubuntu-latest
    # if: github.base_ref == 'homolog'
    steps:
      - name: automerge no buytrip-ci-automerge
        uses: actions/github-script@0.20
        with:
          script: |
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{github.token}}
