name: BuyTrip CI Automerge

on:

  pull_request:
    branches:
      - homolog

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.base_ref == 'homolog' && github.actor == 'dependabot[bot]'
    steps:
      - name: automerge no buytrip-ci-automerge
        uses: "pascalgn/automerge-action@80acb0f883348dcfd0e526288f7d27a12b9333be"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "Tested"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
