name: BuyTrip CI

on:
  
  push:
    branches-ignore: [master, homolog]
    pull_request:
      branches: [homolog]
      types: [opened, synchronize, closed]
#     types:
#       - labeled
#       - unlabeled
#       - synchronize
#       - opened
#       - edited
#       - ready_for_review
#       - reopened
#       - unlocked
#   pull_request_review:
#     types:
#       - submitted
#   check_suite:
#     types:
#       - completed
#   status: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Maven Package
      # run: mvn -B clean package --file pom.xml
      run: mvn -version


  pull-request:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request to homolog
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""                                  
        destination_branch: "homolog"                      
        pr_title: "Pulling ${{ github.ref }} into homolog" 
        pr_label: ""

        github_token: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    needs: 
      - pull_request
    runs-on: ubuntu-latest
    steps:

      - name: automerge no buytrip-ci-github
        uses: "pascalgn/automerge-action@80acb0f883348dcfd0e526288f7d27a12b9333be"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "Tested"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
